language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
sudo: true
cache: 
    - apt
    - pip
# command to install dependencies
install:
    - travis_wait ./install.sh
# command to run tests
script: 
    - ./lint.sh

